### ISSUE TITLE
Admin link leading to 404 if HumHub is installed in a subdirectory

### ISSUE THREAD

**Issue by pheraph** [GreenMeteor/verified#21]
The module's admin link refers to `/verified/admin/index`, but should refer to `/installpath/verified/admin/index`

**Comment by felixhahnweilheim** [comment]
Thanks for the bug report. I think this commit will fix it: https://github.com/GreenMeteor/verified/commit/6af08c8ed6be77f6ee5017e5cede78d4c0b9906a

It isn't merged yet.

**Comment by justinsanjp** [comment]
how i can fix this on my own?, im ussing the current version from the humhub marketplace, and this bug issent fixed.

**Comment by justinsanjp** [comment]
Thanks! It works!

**Comment by ArchBlood** [comment]
The next version release date will more than likely be next Friday (i.e. Friday after this Friday) on GitHub then on the marketplace it takes up to 3 business days for review, so expect the marketplace upload version to be out after it's reviewed.
