### ISSUE TITLE
Option to turn off payed verification, or to include both payed and verified verification.

### ISSUE THREAD

**Issue by kyanzwick** [GreenMeteor/verified#27]
I thought that verification would be implemented with an ID upload sort of system, where users can request verification, and admins could reject or accept the request. I see now there is a payed option, like on twitter or meta. However, there should still be the option for ID image upload  / traditional verificaiton. Maybe if they could be implemented alongside each other. So if someone wants one or the other or both types of verification, it would just work? Would be great to see this implemented. Thanks

**Comment by kyanzwick** [comment]
Adding onto this, maybe it would fit well as another button next to payment options, and like payment verification, have the settings inside and the ability to turn it on and off.

**Comment by felixhahnweilheim** [comment]
The payment can already be turned off. Just uncheck the "Enable" checkbox in the payment options page.

For the other request, I don't know if @ArchBlood is still working on an additional form.

**Comment by ArchBlood** [comment]
By default the payment option is disabled, as for the ID upload option, this requires a lot of legal work and knowledge of actually verifying that an ID is authentic and not a fake. This is why this wasn't implemented.

Other options could be added but aren't currently in the works.

**Comment by kyanzwick** [comment]
Oh I see. Maybe a simpler version of this sort of thing could be implemented, like requesting verification. For instance the flow would be like so:  in the verification tab of your profile, you could request verificaiton, then an admin could either accept or deny request. Then have some code that will revoke their verification when the user changes their username, firstname, or lastname. Would be a pretty good system because atleast users could request the verification, and once they get it they couldn't just change their name to pretend to be someone else.

**Comment by ArchBlood** [comment]
> Oh I see. Maybe a simpler version of this sort of thing could be implemented, like requesting verification. For instance the flow would be like so: in the verification tab of your profile, you could request verificaiton, then an admin could either accept or deny request. Then have some code that will revoke their verification when the user changes their username, firstname, or lastname. Would be a pretty good system because atleast users could request the verification, and once they get it they couldn't just change their name to pretend to be someone else.

Maybe in the future, but currently not on out to-do list.

**Comment by ArchBlood** [comment]
> Oh I see. Maybe a simpler version of this sort of thing could be implemented, like requesting verification. For instance the flow would be like so: in the verification tab of your profile, you could request verificaiton, then an admin could either accept or deny request. Then have some code that will revoke their verification when the user changes their username, firstname, or lastname. Would be a pretty good system because atleast users could request the verification, and once they get it they couldn't just change their name to pretend to be someone else.

Maybe in the future, but currently not on out to-do list.
