### ISSUE TITLE
Verified user label not translated

### ISSUE THREAD

**Issue by PeopleInside** [GreenMeteor/verified#28]
**Describe the bug**

**To Reproduce**
My community is using the Italian language.
The label of verified users are not in my forum language and I don't see a way to translate it.

**Expected behavior**
Be able to see verified user translated in the forum language.

**Screenshots**

![immagine](https://github.com/GreenMeteor/verified/assets/5006150/23d68827-783b-4670-b4cb-e197e70ed8bc)

**Additional context**
Any suggestion to edit the code and fix this on my install?

**Comment by PeopleInside** [comment]
Found where need to insert the translation: /protected/modules/verified/messages/it/
Closing the issue

**Comment by felixhahnweilheim** [comment]
And feel free to create a PR to add the translation.
